### ISSUE TITLE
Rewrite documentation on colors

### ISSUE THREAD

**Issue by lwu877** [PHSWireClippers5902/website-guidelines#1]
As of now, most of the documentation is in varying states of disarray on a Google Doc. I'm working on getting all of the information onto GitHub simply so it can be deployed as a GitHub page and stored for all eternity - while still being easily accessible by writers. 

This task requires some knowledge on creating a table in Markdown, but it's relatively simple.

**Comment by martincarapia** [comment]
I don't see any document on colors to rewrite. Can you point me to the right spot?

**Comment by lwu877** [comment]
It's in our internal drive, under General Team -> Website -> Website/Design Standards.
It's not necessarily difficult per se - it's just that markdown tables are a little tedious. 

If someone from the team would like to help me out with this, that'd be great. This isn't the type of issue that we'd need external help on, but thanks for offering! (Really, none of this repo needs external help - it's just good to plan all this out somewhere.)

**Comment by martincarapia** [comment]
I'm just bug hunting so it's no big deal.

**Comment by lwu877** [comment]
Right, just got that out of the way.
These docs should be completely ready to onboard new members.
